//
// Created by Egor Orachyov on 2019-10-15.
//

#ifndef VULKANRENDERER_COMPILATION_H
#define VULKANRENDERER_COMPILATION_H

#ifndef MODE_DEBUG
    #define MODE_DEBUG
#endif

#endif //VULKANRENDERER_COMPILATION_H
