image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ignimbrite
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x64

configuration:
  - Debug

environment:
  matrix:
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w64
      ARCH: x64

install:
  # Install Vulkan SDK
  - curl -L --output VulkanSDK.exe
    https://sdk.lunarg.com/sdk/download/1.1.130.0/windows/VulkanSDK-1.1.130.0-Installer.exe?Human=true
  - start .\VulkanSDK /S
  - set VULKAN_SDK="C:\VulkanSDK\1.1.130.0"

  # Rename sh.exe as sh.exe in PATH interferes with MinGW
  - rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

  # Configure MinGW 64
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin;C:\mingw64;C:\mingw-w64;%PATH%

build_script:
  # Build library and tests
  - mkdir build
  - cd build

  - if [%COMPILER%]==[MinGW-w64] cmake .. -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\ming-w64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
    -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES

  - cmake --build .