image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ignimbrite
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x64

configuration:
  - Debug

environment:
  matrix:
    - TOOLCHAIN: mcvs14
      BUILD_TYPE: Debug

install:
  # Install Vulkan SDK
  - curl -L --output VulkanSDK.exe
    https://sdk.lunarg.com/sdk/download/1.1.130.0/windows/VulkanSDK-1.1.130.0-Installer.exe?Human=true
  - start .\VulkanSDK /S
  - set VULKAN_SDK="C:\VulkanSDK\1.1.130.0"

build_script:
  # Build library and tests
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS% -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
    -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES

  - cmake --build .