image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ignimbrite
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x64

configuration:
  - Debug

environment:
  matrix:
    - ARCH: x64
      COMPILER: MinGW

install:
  # Install Vulkan SDK
  - curl -L --output VulkanSDK.exe
    https://sdk.lunarg.com/sdk/download/1.1.130.0/windows/VulkanSDK-1.1.130.0-Installer.exe?Human=true
  - start .\VulkanSDK /S

build_script:
  # Build library and tests
  - mkdir build
  - cd build
  - cmake -E env VULKAN_SDK="C:\VulkanSDK\1.1.130.0"
    cmake .. %CMAKE_CONFIGURE_FLAGS% -DCMAKE_BUILD_TYPE=Debug -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES
  - cmake --build .