//
// Created by Egor Orachyov on 2019-10-15.
//

#ifndef IGNIMBRITELIBRARY_COMPILATION_H
#define IGNIMBRITELIBRARY_COMPILATION_H

#ifndef MODE_DEBUG
    #define MODE_DEBUG
#endif

#endif //IGNIMBRITELIBRARY_COMPILATION_H
