#ifndef IGNIMBRITELIBRARY_OPTIONS_H
#define IGNIMBRITELIBRARY_OPTIONS_H

#define WITH_GLFW
/* #undef WITH_GLM */
#define WITH_VULKAN
/* #undef WITH_SPIRVCROSS */

#define IgnimbriteLibrary_VERSION_MAJOR 1
#define IgnimbriteLibrary_VERSION_MINOR 0

#endif // IGNIMBRITELIBRARY_OPTIONS_H
