name: Linux

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:
    branches:
      - master
      - development
      - release

jobs:
  build:
    runs-on: macos

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j
