name: Linux

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:
    branches:
      - master
      - development
      - release

jobs:
  build:
    runs-on: macos

    steps:
      - uses: actions/checkout@v1
      - name: Install Vulkan SDK
        run: |
          sudo apt update
          sudo apt dist-upgrade
          mkdir vulkan
          wget -O sdk.tar.gz "https://sdk.lunarg.com/sdk/download/1.1.130.0/linux/vulkansdk-sdk.tar.gz?u="
          tar -C vulkan -xf sdk.tar.gz
          cd vulkan/1.1.130.0
          sh setup-env.sh
      - name: Build library modules and tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES
          make -j
