name: Linux

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:
    branches:
      - master
      - development
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Instal GLFW dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxrandr-dev libxinerama-dev xorg-dev
      - name: Install Vulkan SDK
        run: |
          mkdir vulkan
          wget -O sdk.tar.gz "https://sdk.lunarg.com/sdk/download/1.1.130.0/linux/vulkansdk-sdk.tar.gz?Human=true"
          tar -C vulkan -xf sdk.tar.gz
          cd vulkan/1.1.130.0
          VULKAN_SDK="$PWD/x86_64"
          PATH="$VULKAN_SDK/bin:$PATH"
          LD_LIBRARY_PATH="$VULKAN_SDK/lib:${LD_LIBRARY_PATH:-}"
          VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"
          echo "VULKAN_SDK=$VULKAN_SDK" >> ~/.bash_profile
          echo "PATH=$PATH" >> ~/.bash_profile
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> ~/.bash_profile
          echo "VK_LAYER_PATH=$VK_LAYER_PATH" >> ~/.bash_profile
          source ~/.bash_profile
      - name: Build library modules and tests
        run: |
          source ~/.bash_profile
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES
          make -j
