name: MacOS

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:
    branches:
      - master
      - development
      - release
  
jobs:
  build:
    runs-on: macos 
  
    steps:
      - uses: actions/checkout@v1
      - name: directoy
        run: |
          mkdir build
          cd build
      - name: build
        run: |
          cmake .. -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES
          make -j
