name: MacOS

on: [push, pull_request]
  
jobs:
  build:
    runs-on: macos 
  
    steps:
      - uses: actions/checkout@v1
      - name: build 
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target Ignimbrite
          cmake --build . --target VulkanDevice
          cmake --build . --target TestObjectID
          cmake --build . --target TestGlfwWindow
          cmake --build . --target TestVulkanApplication
