name: MacOS Build

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
      - release  
  
jobs:
  build:
    runs-on: macos 
  
    steps:
      - uses: actions/checkout@v1
      - name: build 
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target Renderer 
