name: Windows

on:
  pull_request:
    branches:
      - master
      - (26)VkRenderDevice
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          mkdir build
          chdir build
          cmake ..
          cmake --build . --target Ignimbrite
          cmake --build . --target VulkanDevice
          cmake --build . --target TestObjectID
          cmake --build . --target TestGlfwWindow
          cmake --build . --target TestVulkanApplication
