name: Windows

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:
    branches:
      - master
      - development
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Vulkan SDK
        shell: bash
        run: |
          curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.51.0/windows/VulkanSDK-1.0.51.0-Installer.exe?Human=true
          .\VulkanSDK.exe /S
      - name: Build library modules and tests
        run: |
          mkdir build
          chdir build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_GLFW=YES -DWITH_VULKAN=YES -DWITH_TESTS=YES
          cmake --build .
